### ISSUE TITLE
Make required R Version more explicit

### ISSUE THREAD

**Issue by rafabelokurows** [ipeaGIT/uci#13]
First of all, thanks for another great package.

One small suggestion, though: make the R version requirement (>= 4.2.0) clearer to the users in your GitHub page or vignette.

Thanks!

**Comment by rafapereirabr** [comment]
thanks for the suggestion! By default, the R version required by R packages are indicated in the package documentation and in the `DESCRIPTION` file. When installing a package, R will automatically show a message if the local version of R is incompatible with the one required by the package
