### ISSUE TITLE
Function uci() does not work

### ISSUE THREAD

**Issue by retaoliveira** [ipeaGIT/uci#14]
Hi! 

My student has been using the package `uci` to calculate the indicator for her master's dissertation. She has experimented with the code provided as an example with success and has calculated the indicator for the metropolitan areas she is investigating. 

Nevertheless, after the recent actualization, the function `uci()` is not working, not even for the example. 

I have attached some pictures of my screen with the trials. 

Please, let me know if she's doing something wrong or if there is an issue with the function! 

![2023-06-20 16_27_21-centrality - RStudio](https://github.com/ipeaGIT/uci/assets/45176810/ff3f818c-5fee-49f3-afc0-390cb272b19d)
![2023-06-20 16_27_52-centrality - RStudio](https://github.com/ipeaGIT/uci/assets/45176810/7c713894-63b6-4027-8c53-c7bbce9e5980)

Thank you so much!

**Comment by rafapereirabr** [comment]
Hi Renata. Thanks for opening this issue. Could you please run `sessionInfo()` and paste the output in a comment below?

**Comment by rafapereirabr** [comment]
closing this issue due to the lack of response. I'm happy to reopen it if the problem persists
