### ISSUE TITLE
Slight redundancy in `spatial_link` doc

### ISSUE THREAD

**Issue by FlorianNachtigall** [ipeaGIT/uci#15]
Hi @rafapereirabr,

While reading the great documentation, I noticed a small redundancy / relic. Just in case you haven't seen it yet.

https://github.com/ipeaGIT/uci/blob/07627a2ad03bc2624a0d41244004d328c8c99a1e/vignettes/uci.Rmd#L78-L79

https://github.com/ipeaGIT/uci/blob/07627a2ad03bc2624a0d41244004d328c8c99a1e/vignettes/uci.Rmd#L91

**Comment by rafapereirabr** [comment]
thanks for the heads up, @FlorianNachtigall !
